# Configuration of the fuzzing process
[fuzz]
command = "./html_parser @@" 
sanitizer = ["address", "undefined"]

# Environment variables during runtime
[environment]
AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES = "1"

