# Project configurations
[project]
directory = "/src/fuzz-example"    # Directory containing the fuzz target
build = "/src/build.sh"            # Shell script to build the project
command = "/src/html_parser @@"    # Command to run the binary, with @@ replaced by the input file path
tests = "/src/input"               # Directory containing the test cases to evaluate fixes
seeds = "/src/input"               # Directory containing seed files for the fuzzer

# Environment variables during runtime
[environment]
AFL_I_DONT_CARE_ABOUT_MISSING_CRASHES = "1" # Extra environment variable for fuzzing
